#mybatis:
#  mapper-locations: classpath*:/mapper/*.xml
#  type: com.alibaba.druid.pool.DruidDataSource
#  driver-class-name: org.mariadb.jdbc.Driver
#  url: "jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF8"
#  username: root
#  password: root
#  mapper-scan:
#    - com.dante.angular.dao.**
#    - com.dante.angular.dao
#  # 扫描的包（实体类）
#  type-aliases-package: com.dante.angular.entity
spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull"
    mapper-locations: classpath*:/mapper/*.xml
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    mapper-scan:
      - com.dante.angular.dao.**
      - com.dante.angular.dao
    # 扫描的包（实体类）
    type-aliases-package: com.dante.angular.entity
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.dante.angular.entity
